name: Zip into spoon archive
on:
  push:
    branches:
      - main

jobs:
  zip-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make folder
        run: |
          mkdir Spoons
          mkdir Codex.spoon
          cp *.lua Codex.spoon

      - name: Create zip
        run: zip -r -q Spoons/Codex.spoon.zip Codex.spoon

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: '["Spoons/Codex.spoon.zip --force"]'
          message: "Bundle into zip"
          push: origin release --set-upstream --force
          new_branch: release
